"""
源数据画像：扫描 data/grouth_truth/ 下所有真实 Excel，生成 docs/source-profile.md

运行：python src/profile_sources.py
只读源文件，不做任何修改。
"""
import hashlib
from datetime import date
from pathlib import Path

import pandas as pd

BASE_DIR = Path(__file__).resolve().parents[1]
SRC_DIR = BASE_DIR / "data" / "grouth_truth"
OUT = BASE_DIR / "docs" / "source-profile.md"

LINE_TYPES = {"SKU": "product", "DIS": "discount", "IFFSHIP": "freight",
              "FREEGIFT": "gift", "EWALLET": "wallet"}


def num(x):
    """把单元格转成数字；空或非法返回 None"""
    v = pd.to_numeric(x, errors="coerce")
    return None if pd.isna(v) else v


def profile(path):
    df = pd.read_excel(path, header=None, dtype=str)
    labels = df[0].fillna("")
    kind = "price_type" if path.stem.endswith("p") else "detail"
    total = df[labels == "Total"].iloc[0]

    p = {
        "file": path.name,
        "kind": kind,
        "month": df.iloc[0, 1],
        "rows": len(df),
        "sha256": hashlib.sha256(path.read_bytes()).hexdigest()[:12],
        "total_orders": num(total[1]),
        "total_qty": num(total[2]),
        "total_amount": round(num(total[3]), 2),
        # 右边三列 Total 是否和左边三列完全相同（单月报表应当相同）
        "mirror_cols_equal": bool((df.iloc[2:, 1:4].fillna("").values ==
                                   df.iloc[2:, 4:7].fillna("").values).all()),
        "anomalies": [],
    }

    if kind == "detail":
        items = labels[labels.str.startswith("[")]
        codes = items.str.extract(r"^\[([A-Z]+)")[0]
        p["item_rows"] = len(items)
        p["distinct_codes"] = items.str.extract(r"^\[([^\]]+)\]")[0].nunique()
        p["line_types"] = codes.map(LINE_TYPES).fillna("unknown").value_counts().to_dict()
        p["stores"] = [x for x in labels if x and not x.startswith("[")
                       and x not in ("Column0", "Total")]
        detail_amount = round(pd.to_numeric(df.loc[items.index, 3], errors="coerce").sum(), 2)
        p["detail_sum_amount"] = detail_amount
        if detail_amount != p["total_amount"]:
            p["anomalies"].append(f"Detail amount sum {detail_amount} != Total {p['total_amount']}")
        if "unknown" in p["line_types"]:
            p["anomalies"].append("Rows with an unrecognised code prefix")
    else:
        body = df.iloc[2:-1]
        p["price_types"] = body[0].tolist()
        empty = body[body[1].isna()][0].tolist()
        if empty:
            p["anomalies"].append("Empty row (no data): " + ", ".join(empty))

    if not p["mirror_cols_equal"]:
        p["anomalies"].append("Mirrored Total columns differ from the month columns")
    return p


def main():
    files = sorted(SRC_DIR.glob("*.xlsx"))
    profiles = [profile(f) for f in files]
    detail = [p for p in profiles if p["kind"] == "detail"]
    price = {p["month"]: p for p in profiles if p["kind"] == "price_type"}

    lines = [
        "# Source Profile — Legacy Monthly Sales Reports",
        "",
        f"_Generated by `python src/profile_sources.py` on {date.today()}. "
        "Source files are read-only; nothing is modified._",
        "",
        "## 1. Files",
        "",
        "| File | Type | Month | Rows | SHA-256 (12) | Orders | Qty | Amount (NZD) |",
        "|---|---|---|---:|---|---:|---:|---:|",
    ]
    for p in profiles:
        lines.append(f"| `{p['file']}` | {p['kind']} | {p['month']} | {p['rows']} | "
                     f"`{p['sha256']}` | {p['total_orders']:.0f} | {p['total_qty']:.0f} | "
                     f"{p['total_amount']:,.2f} |")

    lines += [
        "",
        "## 2. Layout (all files)",
        "",
        "- Row 1: `Column0 | <Month YYYY> | … | Total | …`; row 2: `Order | Product Quantity | Total Price` (twice).",
        "- Columns 2–4 = the month; columns 5–7 = `Total` across the report period.",
        "- Detail files: one store summary row, then one row per item, then `Total`.",
        "- Price-type files: one row per price type, then `Total`.",
        "- Item text encodes several fields: `[CODE] [Brand]Name (size){variant}`.",
        "",
        "## 3. Detail files",
        "",
        "| Month | Item rows | Distinct codes | product | discount | freight | gift | wallet | Detail sum = Total | Store rows |",
        "|---|---:|---:|---:|---:|---:|---:|---:|---|---|",
    ]
    for p in detail:
        lt = p["line_types"]
        ok = "✅" if p["detail_sum_amount"] == p["total_amount"] else f"❌ {p['detail_sum_amount']}"
        lines.append(f"| {p['month']} | {p['item_rows']} | {p['distinct_codes']} | "
                     f"{lt.get('product', 0)} | {lt.get('discount', 0)} | {lt.get('freight', 0)} | "
                     f"{lt.get('gift', 0)} | {lt.get('wallet', 0)} | {ok} | {', '.join(p['stores'])} |")

    lines += [
        "",
        "## 4. Cross-check: detail report vs price-type report",
        "",
        "| Month | Detail Total (orders / qty / amount) | Price-type Total | Match |",
        "|---|---|---|---|",
    ]
    for p in detail:
        q = price.get(p["month"])
        a = (p["total_orders"], p["total_qty"], p["total_amount"])
        b = (q["total_orders"], q["total_qty"], q["total_amount"]) if q else None
        lines.append(f"| {p['month']} | {a[0]:.0f} / {a[1]:.0f} / {a[2]:,.2f} | "
                     + (f"{b[0]:.0f} / {b[1]:.0f} / {b[2]:,.2f}" if b else "missing")
                     + f" | {'✅' if a == b else '❌'} |")

    all_stores = sorted({s for p in detail for s in p["stores"]})
    price_types = profiles[[p["kind"] for p in profiles].index("price_type")]["price_types"]
    lines += [
        "",
        "## 5. Dimensions available for KPIs",
        "",
        f"- **Store / region:** {len(all_stores)} value(s) across all months: "
        + ", ".join(f"`{s}`" for s in all_stores)
        + ". There is **no region field** — a 'sales by region' KPI cannot be computed from these files.",
        "- **Price type:** " + ", ".join(f"`{t}`" for t in price_types)
        + " (price-type files only; not linked to individual items).",
        "- **Product:** item code, brand, name, size, variant (parsed from item text).",
        "- **Time:** one month per file (Jan–Apr 2026).",
        "",
        "## 6. Anomalies",
        "",
    ]
    anomalies = [(p["file"], a) for p in profiles for a in p["anomalies"]]
    if anomalies:
        lines += [f"- `{f}`: {a}" for f, a in anomalies]
    else:
        lines.append("- None detected.")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n")
    print("\n".join(lines))
    print(f"\n已写出: {OUT}")


if __name__ == "__main__":
    main()
